import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import matplotlib.ticker as ticker
import matplotlib.patches as mpatches
import matplotlib.lines as mlines

# Ensure output directory exists
os.makedirs('src/figures', exist_ok=True)
sns.set_theme(style="whitegrid", palette="muted")

# ==========================================
# 1. Define the user's chosen configurations
# ==========================================
configs = [
    # No Projection
    {'Dataset': 'Emails', 'Projection': 'Standard Pairwise', 'File': 'src/results/emails_aggregated_results.csv', 'Ratio': 0.025, 'Thresh': 0.05},
    {'Dataset': 'StackOverflow', 'Projection': 'Standard Pairwise', 'File': 'src/results/stackoverflow_no_desc_aggregated_results.csv', 'Ratio': 0.075, 'Thresh': 0.01},
    {'Dataset': 'IMDB', 'Projection': 'Standard Pairwise', 'File': 'src/results/imdb_aggregated_results.csv', 'Ratio': 0.025, 'Thresh': 0.05},
    
    # With Projection
    {'Dataset': 'Emails', 'Projection': 'With Domain Projection', 'File': 'src/results/emails_projection_aggregated_results.csv', 'Ratio': 0.025, 'Thresh': 0.05},
    {'Dataset': 'StackOverflow', 'Projection': 'With Domain Projection', 'File': 'src/results/stackoverflow_no_desc_projection_aggregated_results.csv', 'Ratio': 0.025, 'Thresh': 0.05},
    {'Dataset': 'IMDB', 'Projection': 'With Domain Projection', 'File': 'src/results/imdb_projection_aggregated_results.csv', 'Ratio': 0.025, 'Thresh': 0.0},
]

# Extract data specifically for these configurations
results = []
for c in configs:
    if os.path.exists(c['File']):
        df = pd.read_csv(c['File'])
        # Filter for the exact ratio and threshold
        match = df[(df['Ratio'] == c['Ratio']) & ((df['Threshold'] - c['Thresh']).abs() < 0.001)]
        if not match.empty:
            row = match.iloc[0]
            results.append({
                'Dataset': c['Dataset'],
                'Pipeline Variant': c['Projection'],
                'F1 (%)': row['F1 (%)'],
                'Total Tokens': row['Total Tokens']
            })
        else:
            print(f"Warning: No match found for {c['Dataset']} {c['Projection']} (Ratio {c['Ratio']}, Thresh {c['Thresh']})")
    else:
        print(f"File not found: {c['File']}")

plot_df = pd.DataFrame(results)

# ==========================================
# 2. Setup Plot
# ==========================================
fig, ax1 = plt.subplots(figsize=(12, 7))

dataset_order = ['Emails', 'StackOverflow', 'IMDB']
hue_order = ['Standard Pairwise', 'With Domain Projection']

bar_palette = sns.color_palette("pastel", 2)
line_palette = sns.color_palette("dark", 2)

# Plot Bars (F1 Score) on primary y-axis
sns.barplot(
    data=plot_df, 
    x='Dataset', 
    y='F1 (%)', 
    hue='Pipeline Variant', 
    hue_order=hue_order,
    ax=ax1, 
    palette=bar_palette,
    edgecolor='black'
)

# Configure primary y-axis (F1 Score)
ax1.set_xlabel('Dataset', fontsize=12, fontweight='bold', labelpad=10)
ax1.set_ylabel('F1 Score (%)', fontsize=12, fontweight='bold', labelpad=10)
ax1.set_ylim(0, 100)
ax1.grid(axis='y', linestyle='--', alpha=0.7)

# Create twin axis for Tokens
ax2 = ax1.twinx()

# Plot Lines (Tokens) on secondary y-axis using pointplot for exact dodge alignment
sns.pointplot(
    data=plot_df,
    x='Dataset',
    y='Total Tokens',
    hue='Pipeline Variant',
    hue_order=hue_order,
    ax=ax2,
    palette=line_palette,
    dodge=0.4, # Match the barplot dodge width
    markers=['o', 's'],
    linestyles=['-', '--'],
    scale=1.5
)

# Configure secondary y-axis (Tokens)
ax2.set_ylabel('Total Token Expenditure', fontsize=12, fontweight='bold', labelpad=10)
ax2.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, p: format(int(x), ',')))
ax2.grid(False) 

# ==========================================
# 3. Custom Unified Legend
# ==========================================
# Clean up duplicate default legends generated by seaborn
if ax1.legend_ is not None:
    ax1.legend_.remove() 
if ax2.legend_ is not None:
    ax2.legend_.remove() 

custom_handles = []
for i, variant in enumerate(hue_order):
    bar_patch = mpatches.Patch(facecolor=bar_palette[i], edgecolor='black')
    line_marker = mlines.Line2D([], [], color=line_palette[i], marker=['o', 's'][i], linestyle=['-', '--'][i], markersize=8, linewidth=2)
    custom_handles.append((bar_patch, line_marker))

fig.legend(
    handles=custom_handles, 
    labels=hue_order, 
    loc='upper center', 
    bbox_to_anchor=(0.5, .85), # 1. Lowered the legend slightly (was 0.95)
    ncol=2, 
    title='Pipeline Variant (Bars = F1 Score, Lines = Token Cost)', 
    title_fontsize='11', 
    fontsize='10',
    frameon=True
)

# Annotate the exact F1 percentages on the bars
for p in ax1.patches:
    height = p.get_height()
    if height > 0:
        ax1.annotate(f"{height:.1f}%", 
                    (p.get_x() + p.get_width() / 2., height), 
                    ha='center', va='bottom', xytext=(0, 5), 
                    textcoords='offset points', fontweight='bold')

# 2. Increased pad to push the title safely above the legend
plt.title('Optimal Configurations: Standard Pairwise vs. Projection', fontsize=16, fontweight='bold', pad=70)

plt.tight_layout()

# 3. Squished the top of the plot down further to make room for the stacked text
plt.subplots_adjust(top=0.75) 

filepath = 'src/figures/optimal_projection_comparison.png'
plt.savefig(filepath, dpi=300, bbox_inches='tight')
print(f"Successfully generated: {filepath}")